const brands = [
  "Aadyam Handwoven",
  "Aanam",
  "Abraham & Thakore",
  "Accessorize",
  "Adidas",
  "AKOK",
  "Aldo",
  "Allen Solly",
  "American Eagle",
  "Amessio",
  "AND Global Desi",
  "Anita Dongre",
  "Anokhi",
  "Armani Exchange",
  "Arrow",
  "Asics",
  "Aurelia",
  "Bare Denim",
  "Basics",
  "Bata",
  "Being Human",
  "Bershka",
  "Biba",
  "BlackBerrys",
  "Blahblahblah Clothing",
  "Bloni",
  "Blushlace",
  "Boss",
  "Bottega Veneta",
  "Brooks Brothers",
  "Burberry",
  "CAI",
  "Calvin Klein",
  "Canali",
  "Caratlane",
  "Casio",
  "Celio",
  "Chanel",
  "Charles & Keith",
  "Charles Tyrwhitt",
  "Cltr Studios",
  "Coach",
  "Colour Plus",
  "Columbia Sportswear",
  "Cottonworld",
  "Crocs",
  "Curio Cottage",
  "Daysforclothing (DFC)",
  "Delsey",
  "Diesel",
  "Dior",
  "Dune London",
  "Ecco",
  "Emporio Armani",
  "Enrich",
  "Essentrix",
  "Esthreall",
  "Ethos Summit",
  "Evemen",
  "FabIndia",
  "FableStreet",
  "Fastrack",
  "Fekki",
  "FiftyEight",
  "Firvt",
  "Fitflop",
  "Fizzy Goblet",
  "Flying Machine",
  "Forever 21",
  "Forever New",
  "Fossil",
  "Franck Muller",
  "Freeze Studios",
  "GANT",
  "GAP",
  "Garuda SS",
  "GAS",
  "Genes",
  "Giva",
  "Global Desi",
  "Go Colors",
  "Godson Studios",
  "GoSriKi",
  "Gucci",
  "Guess",
  "H&M",
  "Hackett London",
  "Hamster London",
  "Helios Watches",
  "Hidesign",
  "House Of Pataudi",
  "Hublot",
  "Huemn",
  "Hunkemoller",
  "Hush Puppies",
  "Inc. 5",
  "Indian Terrain",
  "Isharya",
  "IT Luggage",
  "Izod",
  "Jacadi Paris",
  "Jack & Jones",
  "Jacob & Co",
  "Jammer.co.in",
  "Jay’s Watch Store",
  "Jaypore",
  "Jimmy Choo",
  "Jockey",
  "John Miller",
  "John Players",
  "Jolaa",
  "Kalyan Jewellers",
  "Kappa",
  "Kazo",
  "KGL",
  "Khadim's",
  "La Martina",
  "Lab88",
  "Lacoste",
  "Lakhani",
  "Lancer",
  "Lashkaraa",
  "Leavetherest",
  "Les Petits",
  "Levi's",
  "Libas",
  "Liberty",
  "Little Tags Luxury",
  "Locos",
  "Lombard",
  "Lost My Accent",
  "Louis Philippe",
  "Madame",
  "MaincharacterIndia",
  "Malabar Gold",
  "Mango",
  "Manish Malhotra",
  "Marks & Spencer",
  "Masaba",
  "Massimo Dutti",
  "Max Fashion",
  "Melissa",
  "Metro Shoes",
  "Mia By Tanishq",
  "Michael Kors",
  "Mogra",
  "Mokobara",
  "Moonray",
  "Moral Science",
  "Mothercare",
  "Mufti",
  "Nappa Dori",
  "Natty Grab",
  "Nautica",
  "Navyasa",
  "Nicobar",
  "Nike",
  "Omega",
  "Onitsuka Tiger",
  "Only",
  "ORRA",
  "Outbreak Lab",
  "Outhouse Jewellery",
  "Owr Life",
  "Panerai",
  "Pantaloons",
  "Paragon",
  "Park Avenue",
  "Parx",
  "Pepe Jeans",
  "Peter England",
  "Polo Ralph Lauren",
  "Provogue",
  "Puma",
  "PvtLtd",
  "Rado",
  "Raghavendra Rathore",
  "Ranna Gill",
  "Rare Rabbit",
  "Rareism",
  "Ray-Ban",
  "Raymond",
  "Red Tape",
  "Reebok",
  "Ripoff",
  "Rishta",
  "Ritu Kumar",
  "Salt Attire",
  "Salvatore Ferragamo",
  "Samsonite",
  "Satya Paul",
  "Scotch & Soda",
  "Seedstore",
  "Selected Homme",
  "Shantanu & Nikhil",
  "Skechers",
  "Soch",
  "Souled Store",
  "Southwave",
  "Speedo",
  "Spykar",
  "Steve Madden",
  "Stylistico",
  "Sunglass Hut",
  "Superdry",
  "Superstreet",
  "Supervintage",
  "Swarovski",
  "Swatch",
  "Swawe",
  "Tanishq",
  "Tarun Tahiliani",
  "Ted Baker",
  "The Collective",
  "The Misnomer",
  "TheFlames",
  "Tirumala Footwear",
  "Tissot",
  "Titan",
  "Tod's",
  "Toffle",
  "Tommy Hilfiger",
  "Tresmode",
  "Tribe By Amrapali",
  "Triumph",
  "True Religion",
  "Tumi",
  "Two Point Two Studios",
  "Under Armour",
  "Uniqlo",
  "United Colors of Benetton",
  "Unreborn Project",
  "Urban Monkey",
  "US Polo Assn",
  "Van Heusen",
  "Vero Moda",
  "Victoria’s Secret",
  "VIP",
  "VKC Pride",
  "Void Clothing",
  "W for Woman",
  "Wacoal",
  "Whattheflex",
  "Wildcraft",
  "William Penn",
  "Woodland",
  "Zara",
  "Zegna",
  "Zivame",
  "Zodiac",
  "Zodok",
  "Zoya",
];

export default brands;